services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_app
      POSTGRES_PASSWORD: "i0vNeB59NSLE82C7lqKvFBm_bLf9tfl4"
    volumes:
      - todo_app_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "p-Fnj5JZ7crPIUNor2wAyGRz9RiI6j26"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_app_test
      POSTGRES_PASSWORD: "thI_RI_CeOnQBqMq1iohmPTY6PeBMxZJ"
    volumes:
      - todo_app_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "E-bWbaC-5LDxOU-FEKesfcKM8ymPd-hW"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  todo_app_data:
  todo_app_test_data:
